export const products = [{
    img: '/img/products/1.jpg',
    name: 'Large Bagged Oranges',
    stars: '45',
    reviews: 3,
    hasSale: true,
    salePercent: 75,
    discountPrice: 260,
    price: 350,
    status: true,
}, {
    img: '/img/products/1.jpg',
    name: 'Large Bagged Oranges',
    stars: '45',
    reviews: 3,
    hasSale: true,
    discountPrice: 360,
    price: 450,
    status: false,
}, {
    img: '/img/products/1.jpg',
    name: 'Large Bagged Oranges',
    stars: '45',
    reviews: 3,
    hasSale: true,
    discountPrice: 360,
    price: 450,
    status: false,
}, {
    img: '/img/products/1.jpg',
    name: 'Large Bagged Oranges',
    stars: '45',
    reviews: 3,
    hasSale: true,
    discountPrice: 360,
    price: 450,
    status: false,
}, {
    img: '/img/products/1.jpg',
    name: 'Large Bagged Oranges',
    stars: '45',
    reviews: 3,
    hasSale: true,
    discountPrice: 360,
    price: 450,
    status: false,
}, {
    img: '/img/products/1.jpg',
    name: 'Large Bagged Oranges',
    stars: '45',
    reviews: 3,
    hasSale: true,
    discountPrice: 360,
    price: 450,
    status: false,
}, {
    img: '/img/products/1.jpg',
    name: 'Large Bagged Oranges',
    stars: '45',
    reviews: 3,
    hasSale: true,
    discountPrice: 360,
    price: 450,
    status: false,
}, {
    img: '/img/products/1.jpg',
    name: 'Large Bagged Oranges',
    stars: '45',
    reviews: 3,
    hasSale: true,
    discountPrice: 360,
    price: 450,
    status: false,
}];